services:
  web:
    build: ./app
    ports:
      - "8127:5000"
    environment:
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy  # Ensures that the web service waits until db is healthy
    restart: always
    networks:
      - default

  db:
    image: postgres:latest
    build: ./db  # Assuming you want to build a custom PostgreSQL image from ./db directory
    ports:
      - "8269:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistent volume for database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - default

volumes:
  db_data: 

networks:
  default:
    driver: bridge
