FROM python:3.12-slim

WORKDIR /app

COPY . /app

# RUN echo $(ls -1 /app)

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8127

CMD ["flask", "run", "--host=0.0.0.0", "--port=8127"]