FROM python:3.13-slim

WORKDIR /app

# Reduce layer size and optimize package installation
RUN apt-get update && apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/* && pip install -U pip

# Set environment variables in a single instruction
ENV CONTEXT_PATH=./../data/context.txt \
    GIVEN_CONTEXT_PATH=./../data/g_context.txt \
    WEATHER_CONTEXT_PATH=./../data/w_context.txt \
    SCRAPE_CONTEXT_PATH=./../data/s_context.txt \
    LATITUDE=40.110558 \
    LONGITUDE=-88.228333 \
    IP=172.20.10.2

# Copy only requirements first to leverage Docker cache
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . /app

EXPOSE 8127

WORKDIR /app/src

CMD ["flask", "run", "--host=0.0.0.0", "--port=8127"]
